"""bluebikes_top3_opt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qiL45y39BwI5S68mGQhV1RT5Gbtqw1B

# Notebook Setup
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import pandas as pd
from tqdm import tqdm
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score, make_scorer
import matplotlib.pyplot as plt
import seaborn as sns
import itertools

# Path to data folder
DATA_DIR = '/content/drive/MyDrive/bluebikes_2024/bluebikes_2024_data'

"""# Explore"""

file_path = f'{DATA_DIR}/top3_merged_all_months.csv'
df = pd.read_csv(file_path)

df.shape

df.head()

df.tail()

"""# Aggregate trips (outbound/starting stations)"""

# Parse timestamps safely
df['started_at'] = pd.to_datetime(df['started_at'], format='mixed', errors='coerce')
df['date'] = df['started_at'].dt.date

# Filter for the 3 target stations
allowed = [
    "MIT at Mass Ave / Amherst St",
    "Harvard Square at Mass Ave/ Dunster",
    "Central Square at Mass Ave / Essex St"
]
df_f = df[df['start_station_name'].isin(allowed)].copy()

# Add time-related features
df_f['day_of_week'] = df_f['started_at'].dt.day_name()
df_f['is_weekend'] = df_f['day_of_week'].isin(['Saturday', 'Sunday'])
df_f['week_of_year'] = df_f['started_at'].dt.isocalendar().week
df_f['month'] = df_f['started_at'].dt.month_name()

# Group to trip counts
outbound = (
    df_f.groupby(['start_station_name', 'date', 'hour',
                  'day_of_week', 'is_weekend', 'week_of_year', 'month'])
        .size()
        .reset_index(name='trip_count')
)

outbound.head(20)

outbound.shape

# === 1. Build full grid ===
stations = outbound['start_station_name'].unique()   # use pre-dummy outbound, not outbound_encoded
dates = outbound['date'].unique()
hours = sorted(outbound['hour'].unique())

full_grid = pd.MultiIndex.from_product(
    [stations, dates, hours],
    names=['start_station_name', 'date', 'hour']
).to_frame(index=False)

# === 2. Merge only trip counts ===
merged = pd.merge(
    full_grid,
    outbound[['start_station_name', 'date', 'hour', 'trip_count']],  # no dummy cols
    on=['start_station_name', 'date', 'hour'],
    how='left'
)

# Fill trip_count = 0 for missing combinations
merged['trip_count'] = merged['trip_count'].fillna(0)

# === 3. Recompute all temporal features from date ===
merged['date'] = pd.to_datetime(merged['date'])
merged['day_of_week'] = merged['date'].dt.day_name()
merged['is_weekend'] = merged['day_of_week'].isin(['Saturday', 'Sunday'])
merged['week_of_year'] = merged['date'].dt.isocalendar().week
merged['month'] = merged['date'].dt.month_name()

merged.head(10)

merged.to_csv(f'{DATA_DIR}/top3_agg_outbound.csv', index=False)

# One-hot encode categorical variables
outbound_encoded = pd.get_dummies(
    outbound,
    columns=['day_of_week', 'week_of_year', 'month'],
    drop_first=False,
    dtype=int
)

"""# Model

## Original data loading
"""

file_path = f'{DATA_DIR}/top3_agg_outbound.csv'
merged = pd.read_csv(file_path)

# === One-hot encode after recomputation ===
complete_df = pd.get_dummies(
    merged,
    columns=['start_station_name', 'day_of_week', 'week_of_year', 'month', 'hour'],
    prefix=['station', 'day', 'week', 'month', 'hour'],
    drop_first=False,   # keep all dummies for flexibility
    dtype=int
)

complete_df.head(10)

print(complete_df.columns.tolist())

complete_df.shape

"""## Linear Regression"""

# Copy to avoid modifying original
df = complete_df.copy()

# Define target and features
y = df['trip_count']
X = df.drop(columns=['trip_count', 'date', 'is_weekend'], errors='ignore')

# Drop baseline dummies (to avoid multicollinearity)=
baseline_dummies = [
    'day_Monday',                                    # baseline for day_of_week
    'month_January',                                # baseline for month
    'station_MIT at Mass Ave / Amherst St',          # baseline for station
    'week_1',                                        # baseline for week_of_year
    'hour_0'                                        # baseline for hour
]

# Drop these explicitly
X = X.drop(columns=baseline_dummies, errors='ignore')

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train linear regression
lr = LinearRegression()
lr.fit(X_train, y_train)

# Predict on both train and test
y_train_pred = lr.predict(X_train)
y_test_pred  = lr.predict(X_test)

# Compute metrics
train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
test_rmse  = np.sqrt(mean_squared_error(y_test, y_test_pred))
train_r2   = r2_score(y_train, y_train_pred)
test_r2    = r2_score(y_test, y_test_pred)

# Print results
print("Linear Regression Performance:")
print(f"Train RMSE: {train_rmse:.3f} | Train R²: {train_r2:.3f}")
print(f"Test  RMSE: {test_rmse:.3f} | Test  R²: {test_r2:.3f}")

# Inspect coefficients
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': lr.coef_
}).sort_values('Coefficient', ascending=False)

print("\nTop 10 positive predictors:")
print(coef_df.head(10))

print("\nTop 10 negative predictors:")
print(coef_df.tail(10))

import statsmodels.api as sm

# Fit OLS model on training data
ols_model = sm.OLS(y_train, X_train).fit()

# Predict on both training and test data
y_train_pred = ols_model.predict(X_train)
y_test_pred = ols_model.predict(X_test)

# Compute RMSE and R² for both sets
train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

# Print performance metrics
print(f"Train RMSE: {train_rmse:.3f}")
print(f"Train R²:   {train_r2:.3f}")
print(f"Test RMSE:  {test_rmse:.3f}")
print(f"Test R²:    {test_r2:.3f}\n")

# Print full regression summary
print(ols_model.summary())

def print_ols_summary_with_stars(model):
    res = model
    table = pd.DataFrame({
        'coef': res.params,
        'std err': res.bse,
        't': res.tvalues,
        'P>|t|': res.pvalues
    })

    def star(p):
        if p < 0.01: return '***'
        elif p < 0.05: return '**'
        elif p < 0.10: return '*'
        else: return ''

    table[''] = table['P>|t|'].apply(star)
    table = table.round({'coef':3, 'std err':3, 't':2, 'P>|t|':4})

    print("\nCoefficients:")
    print(table.to_string(justify='left'))
    print("\n---")
    print("Signif. codes:  *** p<0.01, ** p<0.05, * p<0.1")

# usage:
print_ols_summary_with_stars(ols_model)

corr = X.corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr, cmap='coolwarm', center=0)
plt.title('Feature Correlation Heatmap')
plt.show()

"""### Fix multicollinearity"""

# ⚠️ Need to drop months because multicollinearity with week of year

X = X.drop(columns=[c for c in X.columns if c.startswith('month_')], errors='ignore')

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train linear regression
lr = LinearRegression()
lr.fit(X_train, y_train)

# Predict on both train and test
y_train_pred = lr.predict(X_train)
y_test_pred  = lr.predict(X_test)

# Compute metrics
train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
test_rmse  = np.sqrt(mean_squared_error(y_test, y_test_pred))
train_r2   = r2_score(y_train, y_train_pred)
test_r2    = r2_score(y_test, y_test_pred)

# Print results
print("Linear Regression Performance:")
print(f"Train RMSE: {train_rmse:.3f} | Train R²: {train_r2:.3f}")
print(f"Test  RMSE: {test_rmse:.3f} | Test  R²: {test_r2:.3f}")

# Inspect coefficients
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': lr.coef_
}).sort_values('Coefficient', ascending=False)

print("\nTop 10 positive predictors:")
print(coef_df.head(10))

print("\nTop 10 negative predictors:")
print(coef_df.tail(10))

X.head()

# Fit OLS model on training data
ols_model = sm.OLS(y_train, X_train).fit()

# Predict on both training and test data
y_train_pred = ols_model.predict(X_train)
y_test_pred = ols_model.predict(X_test)

# Compute RMSE and R² for both sets
train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

# Print performance metrics
print(f"Train RMSE: {train_rmse:.3f}")
print(f"Train R²:   {train_r2:.3f}")
print(f"Test RMSE:  {test_rmse:.3f}")
print(f"Test R²:    {test_r2:.3f}\n")

print_ols_summary_with_stars(ols_model)

corr = X.corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr, cmap='coolwarm', center=0)
plt.title('Feature Correlation Heatmap')
plt.show()

"""### Ridge and Lasso"""

# Split 80/20 for final evaluation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# CV setup
kf = KFold(n_splits=5, shuffle=True, random_state=42)
rmse_scorer = make_scorer(lambda y_true, y_pred: np.sqrt(mean_squared_error(y_true, y_pred)),
                          greater_is_better=False)
r2_scorer = make_scorer(r2_score)

# Model parameter grids
param_grid = {
    'Ridge': {'model': Ridge(), 'params': {'alpha': [0.0001, 0.001, 0.01, 0.1, 1, 5, 10]}},
    'Lasso': {'model': Lasso(max_iter=5000), 'params': {'alpha': [0.0001, 0.001, 0.01, 0.1]}},
}

# CV → best param → train/test evaluation
for name, entry in tqdm(param_grid.items(), desc="Model families"):
    print(f"\n\n===== {name} =====")
    base_model = entry['model']
    params = entry['params']
    param_results = []

    best_cv_r2 = -np.inf
    best_param = None
    best_model = None

    # --- Step 1: cross-validation for all parameters ---
    for param_name, param_values in params.items():
        for val in param_values:
            model = base_model.set_params(**{param_name: val})
            cv_r2 = cross_val_score(model, X_train, y_train, cv=kf, scoring=r2_scorer, n_jobs=-1).mean()
            param_results.append([f"{param_name}={val}", cv_r2])
            if cv_r2 > best_cv_r2:
                best_cv_r2 = cv_r2
                best_param = {param_name: val}
                best_model = model

    # --- Step 2: show CV R² for all parameters ---
    param_df = pd.DataFrame(param_results, columns=['Parameter', 'CV_R2'])
    print(param_df.round(3))
    print(f"\nBest parameter for {name}: {best_param} (CV_R²={best_cv_r2:.3f})")

    # --- Step 3: retrain best model on all training data ---
    best_model.fit(X_train, y_train)
    y_train_pred = best_model.predict(X_train)
    y_test_pred = best_model.predict(X_test)

    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)

    print(f"Train R²: {train_r2:.3f} | Test R²: {test_r2:.3f}")

"""## Other Models"""

file_path = f'{DATA_DIR}/top3_agg_outbound.csv'
merged = pd.read_csv(file_path)

complete_df = pd.get_dummies(
    merged,
    columns=['start_station_name', 'day_of_week', 'week_of_year', 'month', 'hour'],
    prefix=['station', 'day', 'week', 'month', 'hour'],
    drop_first=False,   # keep all dummies for flexibility
    dtype=int
)

# Copy to avoid modifying original
df = complete_df.copy()

# Define target and features
y = df['trip_count']
X = df.drop(
    columns=['trip_count', 'date', 'is_weekend'] +
            [c for c in df.columns if c.startswith('month_')], #drop months
    errors='ignore'
)

X.head()

from tqdm import tqdm

# Split 80/20 for final evaluation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# CV setup
kf = KFold(n_splits=5, shuffle=True, random_state=42)
rmse_scorer = make_scorer(lambda y_true, y_pred: np.sqrt(mean_squared_error(y_true, y_pred)),
                          greater_is_better=False)
r2_scorer = make_scorer(r2_score)

# Model parameter grids
param_grid = {
    'RandomForest': {'model': RandomForestRegressor(random_state=42, n_jobs=-1),
                     'params': {'n_estimators': [50, 100, 150]}},
    'XGBoost': {'model': xgb.XGBRegressor(random_state=42, n_jobs=-1, n_estimators=100),
                'params': {'max_depth': [3, 5, 7]}},
    'GBM': {'model': GradientBoostingRegressor(random_state=42, n_estimators=100),
            'params': {'learning_rate': [0.05, 0.1]}}
}

# CV → best param → train/test evaluation
for name, entry in tqdm(param_grid.items(), desc="Model families"):
    print(f"\n\n===== {name} =====")
    base_model = entry['model']
    params = entry['params']
    param_results = []

    best_cv_r2 = -np.inf
    best_param = None
    best_model = None

    # --- Step 1: cross-validation for all parameters ---
    for param_name, param_values in params.items():
        for val in param_values:
            model = base_model.set_params(**{param_name: val})
            cv_r2 = cross_val_score(model, X_train, y_train, cv=kf, scoring=r2_scorer, n_jobs=-1).mean()
            param_results.append([f"{param_name}={val}", cv_r2])
            if cv_r2 > best_cv_r2:
                best_cv_r2 = cv_r2
                best_param = {param_name: val}
                best_model = model

    # --- Step 2: show CV R² for all parameters ---
    param_df = pd.DataFrame(param_results, columns=['Parameter', 'CV_R2'])
    print(param_df.round(3))
    print(f"\nBest parameter for {name}: {best_param} (CV_R²={best_cv_r2:.3f})")

    # --- Step 3: retrain best model on all training data ---
    best_model.fit(X_train, y_train)
    y_train_pred = best_model.predict(X_train)
    y_test_pred = best_model.predict(X_test)

    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)

    print(f"Train R²: {train_r2:.3f} | Test R²: {test_r2:.3f}")

# XGboost tuning; also clip y to be 0 and above (cannot be negative)

import itertools

param_grid = {
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.5],
    'n_estimators': [100, 150, 200, 300]
}

# Generate all parameter combinations
param_combinations = list(itertools.product(
    param_grid['max_depth'],
    param_grid['learning_rate'],
    param_grid['n_estimators']
))

results = []

# === Grid search loop ===
for (depth, lr, n_est) in tqdm(param_combinations, desc="Grid search progress"):
    params = {'max_depth': depth, 'learning_rate': lr, 'n_estimators': n_est}
    model = xgb.XGBRegressor(random_state=42, n_jobs=-1, **params)

    # --- Cross-validation R² ---
    cv_r2 = cross_val_score(model, X_train, y_train, cv=kf, scoring=r2_scorer, n_jobs=1).mean()

    # --- Train on full training set ---
    model.fit(X_train, y_train)
    y_train_pred = np.maximum(model.predict(X_train), 0)
    y_test_pred  = np.maximum(model.predict(X_test), 0)

    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)

    results.append({
        'max_depth': depth,
        'learning_rate': lr,
        'n_estimators': n_est,
        'Train_R2': train_r2,
        'CV_R2': cv_r2,
        'Test_R2': test_r2
    })

# === Compile results into a DataFrame ===
results_df = pd.DataFrame(results)
results_df = results_df.sort_values('CV_R2', ascending=False).reset_index(drop=True)

print("\n=== XGBoost Grid Search Results ===")
print(results_df.round(3))

# === Identify best configuration ===
best_params = results_df.iloc[0][['max_depth', 'learning_rate', 'n_estimators']].to_dict()
print(f"\nBest parameters: {best_params}")

print("\n=== XGBoost Grid Search Results ===")
print(results_df.round(5))

# === Identify best configuration ===
best_params = results_df.iloc[0][['max_depth', 'learning_rate', 'n_estimators']].to_dict()
print(f"\nBest parameters: {best_params}")

import matplotlib.dates as mdates

# === 1. Refit model on all data ===
best_model = xgb.XGBRegressor(
    random_state=42,
    n_jobs=-1,
    n_estimators=200,
    max_depth=5,
    learning_rate=0.5
)
best_model.fit(X, y)

# === 2. Predict on the full dataset ===
y_pred_full = np.maximum(best_model.predict(X), 0)

# === 3. Combine with original data ===
plot_df = complete_df.copy()
plot_df['predicted'] = y_pred_full
plot_df['actual'] = plot_df['trip_count']

# === 4. Restore station names (from one-hot columns) ===
station_cols = [c for c in plot_df.columns if c.startswith('station_')]
plot_df['station'] = plot_df[station_cols].idxmax(axis=1).str.replace('station_', '')

# === 5. Sort by date and optionally smooth ===
plot_df = plot_df.sort_values('date')
plot_df['actual_smooth'] = plot_df['actual'].rolling(24, center=True).mean()
plot_df['predicted_smooth'] = plot_df['predicted'].rolling(24, center=True).mean()

# === 6. Plot setup ===
stations = plot_df['station'].unique()
n = len(stations)
plt.figure(figsize=(14, 3.5 * n))

for i, station in enumerate(stations, 1):
    subset = plot_df[plot_df['station'] == station]
    plt.subplot(n, 1, i)

    sns.lineplot(data=subset, x='date', y='actual_smooth',
                 color='tab:blue', label='Actual', linewidth=1.8)
    sns.lineplot(data=subset, x='date', y='predicted_smooth',
                 color='tab:orange', label='Predicted', linewidth=1.8)

    plt.title(station)
    plt.ylabel("Trip Count")
    plt.xlabel(None)
    plt.legend()

    # --- Monthly ticks and rotated labels ---
    ax = plt.gca()
    ax.xaxis.set_major_locator(mdates.MonthLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b'))
    plt.xticks(rotation=45, ha='right')

    # --- Remove gridlines ---
    ax.grid(False)

plt.suptitle("Actual vs Predicted Trip Counts by Station (Full Dataset, Smoothed Over Time)",
             fontsize=14, y=0.95)
plt.xlabel("Time (Monthly across the Year)")
plt.tight_layout(rect=[0, 0, 1, 0.94])
plt.show()

"""# Weather"""

file_path = f'{DATA_DIR}/top3_agg_outbound.csv'
merged = pd.read_csv(file_path)

# Merge lat-long coordinates for stations
coords = {
    'MIT at Mass Ave / Amherst St': {'lat': 42.3581, 'lon': -71.093198},
    'Harvard Square at Mass Ave/ Dunster': {'lat': 42.373268, 'lon': -71.118579},
    'Central Square at Mass Ave / Essex St': {'lat': 42.36507, 'lon': -71.1031}
}

merged['lat'] = merged['start_station_name'].map(lambda s: coords[s]['lat'])
merged['lon'] = merged['start_station_name'].map(lambda s: coords[s]['lon'])

merged.head()

pip install openmeteo-requests requests-cache retry-requests numpy pandas

import openmeteo_requests
import requests_cache
from retry_requests import retry
from tqdm import tqdm

# Prepare datetime column
merged['date'] = pd.to_datetime(merged['date'], format='mixed', errors='coerce')
merged['datetime'] = merged['date'] + pd.to_timedelta(merged['hour'], unit='h')

# Open-Meteo client with cache and retry
cache = requests_cache.CachedSession('.cache', expire_after=-1)
session = retry(cache, retries=5, backoff_factor=0.2)
openmeteo = openmeteo_requests.Client(session=session)

# Identify coordinates and time range
unique_coords = merged[['lat', 'lon']].drop_duplicates().to_numpy()
start_date = merged['date'].min().strftime('%Y-%m-%d')
end_date = merged['date'].max().strftime('%Y-%m-%d')

print(f"Fetching weather from {start_date} to {end_date} for {len(unique_coords)} locations...")

weather_frames = []
for lat, lon in tqdm(unique_coords, desc="Downloading weather data"):
    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": start_date,
        "end_date": end_date,
        "hourly": ["temperature_2m", "precipitation", "windspeed_10m"],
        "timezone": "America/New_York"
    }
    resp = openmeteo.weather_api("https://archive-api.open-meteo.com/v1/archive", params=params)[0]
    hourly = resp.Hourly()

    weather_frames.append(pd.DataFrame({
        "datetime": pd.date_range(
            start=pd.to_datetime(hourly.Time(), unit="s", utc=True),
            end=pd.to_datetime(hourly.TimeEnd(), unit="s", utc=True),
            freq=pd.Timedelta(seconds=hourly.Interval()),
            inclusive="left"
        ).tz_convert("America/New_York").tz_localize(None),
        "lat": lat,
        "lon": lon,
        "temperature_2m": hourly.Variables(0).ValuesAsNumpy(),
        "precipitation": hourly.Variables(1).ValuesAsNumpy(),
        "windspeed_10m": hourly.Variables(2).ValuesAsNumpy()
    }))

weather_df = pd.concat(weather_frames, ignore_index=True)

# === Merge trips with weather ===
merged_weather = pd.merge_asof(
    merged.sort_values('datetime'),
    weather_df.sort_values('datetime'),
    on='datetime',
    direction='nearest',
    tolerance=pd.Timedelta('1h')
)

# Drop redundant columns and rename for clarity
merged_weather.drop(columns=[c for c in merged_weather.columns if c.endswith(('_x', '_y'))],
                    inplace=True, errors='ignore')
merged_weather.rename(columns={'lat': 'lat_weather', 'lon': 'lon_weather'}, inplace=True)

print("\n✅ Clean merge completed!")
print(merged_weather[['start_station_name', 'datetime',
                      'temperature_2m', 'precipitation', 'windspeed_10m']].head())

merged_weather.to_csv(f'{DATA_DIR}/top3_with_weather.csv', index=False)

"""# Models with Weather

## Models
"""

file_path = f'{DATA_DIR}/top3_with_weather.csv'
weather = pd.read_csv(file_path)

df = weather.copy()

complete_df = pd.get_dummies(
    df,
    columns=['start_station_name', 'day_of_week', 'week_of_year', 'month', 'hour'],
    prefix=['station', 'day', 'week', 'month', 'hour'],
    drop_first=False,   # keep all dummies for flexibility
    dtype=int
)

for col in complete_df.columns:
    print(col)

complete_df.shape

# Copy to avoid modifying original
df = complete_df.copy()

# Define target and features
y = df['trip_count']
X = df.drop(
    columns=['trip_count', 'date', 'datetime', 'is_weekend'] +
            [c for c in df.columns if c.startswith('month_')], #drop months
    errors='ignore'
)

# Split 80/20 for final evaluation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# CV setup
kf = KFold(n_splits=5, shuffle=True, random_state=42)
rmse_scorer = make_scorer(lambda y_true, y_pred: np.sqrt(mean_squared_error(y_true, y_pred)),
                          greater_is_better=False)
r2_scorer = make_scorer(r2_score)

# Model parameter grids
param_grid = {
    'RandomForest': {'model': RandomForestRegressor(random_state=42, n_jobs=-1),
                     'params': {'n_estimators': [50, 100, 150]}},
    'XGBoost': {'model': xgb.XGBRegressor(random_state=42, n_jobs=-1, n_estimators=100),
                'params': {'max_depth': [3, 5, 7]}},
    'GBM': {'model': GradientBoostingRegressor(random_state=42, n_estimators=100),
            'params': {'learning_rate': [0.05, 0.1]}}
}

# CV → best param → train/test evaluation
for name, entry in tqdm(param_grid.items(), desc="Model families"):
    print(f"\n\n===== {name} =====")
    base_model = entry['model']
    params = entry['params']
    param_results = []

    best_cv_r2 = -np.inf
    best_param = None
    best_model = None

    # --- Step 1: cross-validation for all parameters ---
    for param_name, param_values in params.items():
        for val in param_values:
            model = base_model.set_params(**{param_name: val})
            cv_r2 = cross_val_score(model, X_train, y_train, cv=kf, scoring=r2_scorer, n_jobs=-1).mean()
            param_results.append([f"{param_name}={val}", cv_r2])
            if cv_r2 > best_cv_r2:
                best_cv_r2 = cv_r2
                best_param = {param_name: val}
                best_model = model

    # --- Step 2: show CV R² for all parameters ---
    param_df = pd.DataFrame(param_results, columns=['Parameter', 'CV_R2'])
    print(param_df.round(3))
    print(f"\nBest parameter for {name}: {best_param} (CV_R²={best_cv_r2:.3f})")

    # --- Step 3: retrain best model on all training data ---
    best_model.fit(X_train, y_train)
    y_train_pred = best_model.predict(X_train)
    y_test_pred = best_model.predict(X_test)

    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)

    print(f"Train R²: {train_r2:.3f} | Test R²: {test_r2:.3f}")

corr = X.corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr, cmap='coolwarm', center=0)
plt.title('Feature Correlation Heatmap')
plt.show()

# XGboost tuning; also clip y to be 0 and above (cannot be negative)

import itertools

param_grid = {
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.5],
    'n_estimators': [100, 150, 200, 300]
}

# Generate all parameter combinations
param_combinations = list(itertools.product(
    param_grid['max_depth'],
    param_grid['learning_rate'],
    param_grid['n_estimators']
))

results = []

# === Grid search loop ===
for (depth, lr, n_est) in tqdm(param_combinations, desc="Grid search progress"):
    params = {'max_depth': depth, 'learning_rate': lr, 'n_estimators': n_est}
    model = xgb.XGBRegressor(random_state=42, n_jobs=-1, **params)

    # --- Cross-validation R² ---
    cv_r2 = cross_val_score(model, X_train, y_train, cv=kf, scoring=r2_scorer, n_jobs=1).mean()

    # --- Train on full training set ---
    model.fit(X_train, y_train)
    y_train_pred = np.maximum(model.predict(X_train), 0)
    y_test_pred  = np.maximum(model.predict(X_test), 0)

    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)

    results.append({
        'max_depth': depth,
        'learning_rate': lr,
        'n_estimators': n_est,
        'Train_R2': train_r2,
        'CV_R2': cv_r2,
        'Test_R2': test_r2
    })

# === Compile results into a DataFrame ===
results_df = pd.DataFrame(results)
results_df = results_df.sort_values('CV_R2', ascending=False).reset_index(drop=True)

print("\n=== XGBoost Grid Search Results ===")
print(results_df.round(5))

# === Identify best configuration ===
best_params = results_df.iloc[0][['max_depth', 'learning_rate', 'n_estimators']].to_dict()
print(f"\nBest parameters: {best_params}")

import matplotlib.dates as mdates

# === 1. Refit model on all data ===
best_model = xgb.XGBRegressor(
    random_state=42,
    n_jobs=-1,
    n_estimators=300,
    max_depth=7,
    learning_rate=0.1
)
best_model.fit(X, y)

# === 2. Predict on the full dataset ===
y_pred_full = np.maximum(best_model.predict(X), 0)

# === 3. Combine with original data ===
plot_df = complete_df.copy()
plot_df['predicted'] = y_pred_full
plot_df['actual'] = plot_df['trip_count']

# === 4. Restore station names (from one-hot columns) ===
station_cols = [c for c in plot_df.columns if c.startswith('station_')]
plot_df['station'] = plot_df[station_cols].idxmax(axis=1).str.replace('station_', '')

# === 5. Sort by date and optionally smooth ===
plot_df = plot_df.sort_values('date')
plot_df['actual_smooth'] = plot_df['actual'].rolling(24, center=True).mean()
plot_df['predicted_smooth'] = plot_df['predicted'].rolling(24, center=True).mean()


# === 6. Plot setup ===
stations = plot_df['station'].unique()
n = len(stations)
plt.figure(figsize=(14, 3.5 * n))

for i, station in enumerate(stations, 1):
    subset = plot_df[plot_df['station'] == station]
    plt.subplot(n, 1, i)

    # Plot without CI and slightly offset predicted line for visual separation
    sns.lineplot(
        data=subset, x='date', y='actual_smooth',
        color='tab:blue', label='Actual', linewidth=1.5, errorbar=None
    )
    sns.lineplot(
        data=subset, x='date', y='predicted_smooth',
        color='tab:orange', label='Predicted', linewidth=1.5, errorbar=None, alpha=0.7
    )

    plt.title(station)
    plt.ylabel("Trip Count")
    plt.xlabel(None)
    plt.legend()

    # Monthly ticks, rotate labels
    ax = plt.gca()
    ax.xaxis.set_major_locator(mdates.MonthLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b'))
    plt.xticks(rotation=45, ha='right')

    # Remove background gridlines
    ax.grid(False)

plt.suptitle("Actual vs Predicted Trip Counts by Station (Full Dataset, Smoothed Over Time)",
             fontsize=14, y=0.95)
plt.xlabel("Time (Monthly across the Year)")
plt.tight_layout(rect=[0, 0, 1, 0.94])
plt.show()

"""## Add weather code"""

file_path = f'{DATA_DIR}/top3_agg_outbound.csv'
merged = pd.read_csv(file_path)

# Merge lat-long coordinates for stations
coords = {
    'MIT at Mass Ave / Amherst St': {'lat': 42.3581, 'lon': -71.093198},
    'Harvard Square at Mass Ave/ Dunster': {'lat': 42.373268, 'lon': -71.118579},
    'Central Square at Mass Ave / Essex St': {'lat': 42.36507, 'lon': -71.1031}
}

merged['lat'] = merged['start_station_name'].map(lambda s: coords[s]['lat'])
merged['lon'] = merged['start_station_name'].map(lambda s: coords[s]['lon'])

import openmeteo_requests
import requests_cache
from retry_requests import retry
from tqdm import tqdm

# Prepare datetime column
merged['date'] = pd.to_datetime(merged['date'], format='mixed', errors='coerce')
merged['datetime'] = merged['date'] + pd.to_timedelta(merged['hour'], unit='h')

# Open-Meteo client with cache and retry
cache = requests_cache.CachedSession('.cache', expire_after=-1)
session = retry(cache, retries=5, backoff_factor=0.2)
openmeteo = openmeteo_requests.Client(session=session)

# Identify coordinates and time range
unique_coords = merged[['lat', 'lon']].drop_duplicates().to_numpy()
start_date = merged['date'].min().strftime('%Y-%m-%d')
end_date = merged['date'].max().strftime('%Y-%m-%d')

print(f"Fetching weather from {start_date} to {end_date} for {len(unique_coords)} locations...")

weather_frames = []
for lat, lon in tqdm(unique_coords, desc="Downloading weather data"):
    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": start_date,
        "end_date": end_date,
        "hourly": ["temperature_2m", "precipitation", "windspeed_10m", "weathercode"],
        "timezone": "America/New_York"
    }

    resp = openmeteo.weather_api("https://archive-api.open-meteo.com/v1/archive", params=params)[0]
    hourly = resp.Hourly()

    weather_frames.append(pd.DataFrame({
        "datetime": pd.date_range(
            start=pd.to_datetime(hourly.Time(), unit="s", utc=True),
            end=pd.to_datetime(hourly.TimeEnd(), unit="s", utc=True),
            freq=pd.Timedelta(seconds=hourly.Interval()),
            inclusive="left"
        ).tz_convert("America/New_York").tz_localize(None),
        "lat": lat,
        "lon": lon,
        "temperature_2m": hourly.Variables(0).ValuesAsNumpy(),
        "precipitation": hourly.Variables(1).ValuesAsNumpy(),
        "windspeed_10m": hourly.Variables(2).ValuesAsNumpy(),
        "weathercode": hourly.Variables(3).ValuesAsNumpy()
    }))

weather_df = pd.concat(weather_frames, ignore_index=True)

# === Merge with main dataset ===
merged_weather = pd.merge_asof(
    merged.sort_values('datetime'),
    weather_df.sort_values('datetime'),
    on='datetime',
    direction='nearest',
    tolerance=pd.Timedelta('1h')
)

merged_weather.rename(columns={'lat': 'lat_weather', 'lon': 'lon_weather'}, inplace=True)

print("\n✅ Clean merge completed, now includes weathercode!")
print(merged_weather[['start_station_name', 'datetime',
                      'temperature_2m', 'precipitation', 'windspeed_10m', 'weathercode']].head())

merged_weather.to_csv(f'{DATA_DIR}/top3_with_weather_code.csv', index=False)

# Count unique weather codes
num_weather_types = merged_weather['weathercode'].nunique()
print(f"Number of unique weather codes: {num_weather_types}")

# Count how many rows per code (descending order)
code_counts = merged_weather['weathercode'].value_counts().sort_index()
print("\nRows per weather code:")
print(code_counts)

"""## Models with weather code"""

file_path = f'{DATA_DIR}/top3_with_weather_code.csv'
weather = pd.read_csv(file_path)

df = weather.copy()

complete_df = pd.get_dummies(
    df,
    columns=['start_station_name', 'day_of_week', 'week_of_year', 'month', 'hour','weathercode'],
    prefix=['station', 'day', 'week', 'month', 'hour', 'weathercode'],
    drop_first=False,   # keep all dummies for flexibility
    dtype=int
)

for col in complete_df.columns:
    print(col)

complete_df.shape

# Copy to avoid modifying original
df = complete_df.copy()

# Define target and features
y = df['trip_count']
X = df.drop(
    columns=['trip_count', 'date', 'datetime', 'is_weekend', 'lat_x', 'lon_x', 'lat_y', 'lon_y'] +
            [c for c in df.columns if c.startswith('month_')], #drop months
    errors='ignore'
)

X.shape

# Split 80/20 for final evaluation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# CV setup
kf = KFold(n_splits=5, shuffle=True, random_state=42)
rmse_scorer = make_scorer(lambda y_true, y_pred: np.sqrt(mean_squared_error(y_true, y_pred)),
                          greater_is_better=False)
r2_scorer = make_scorer(r2_score)

# Model parameter grids
param_grid = {
    'RandomForest': {'model': RandomForestRegressor(random_state=42, n_jobs=-1),
                     'params': {'n_estimators': [50, 100, 150]}},
    'XGBoost': {'model': xgb.XGBRegressor(random_state=42, n_jobs=-1, n_estimators=100),
                'params': {'max_depth': [3, 5, 7]}},
    'GBM': {'model': GradientBoostingRegressor(random_state=42, n_estimators=100),
            'params': {'learning_rate': [0.05, 0.1]}}
}

# CV → best param → train/test evaluation
for name, entry in tqdm(param_grid.items(), desc="Model families"):
    print(f"\n\n===== {name} =====")
    base_model = entry['model']
    params = entry['params']
    param_results = []

    best_cv_r2 = -np.inf
    best_param = None
    best_model = None

    # --- Step 1: cross-validation for all parameters ---
    for param_name, param_values in params.items():
        for val in param_values:
            model = base_model.set_params(**{param_name: val})
            cv_r2 = cross_val_score(model, X_train, y_train, cv=kf, scoring=r2_scorer, n_jobs=-1).mean()
            param_results.append([f"{param_name}={val}", cv_r2])
            if cv_r2 > best_cv_r2:
                best_cv_r2 = cv_r2
                best_param = {param_name: val}
                best_model = model

    # --- Step 2: show CV R² for all parameters ---
    param_df = pd.DataFrame(param_results, columns=['Parameter', 'CV_R2'])
    print(param_df.round(3))
    print(f"\nBest parameter for {name}: {best_param} (CV_R²={best_cv_r2:.3f})")

    # --- Step 3: retrain best model on all training data ---
    best_model.fit(X_train, y_train)
    y_train_pred = best_model.predict(X_train)
    y_test_pred = best_model.predict(X_test)

    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)

    print(f"Train R²: {train_r2:.3f} | Test R²: {test_r2:.3f}")

corr = X.corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr, cmap='coolwarm', center=0)
plt.title('Feature Correlation Heatmap')
plt.show()

# XGboost tuning; also clip y to be 0 and above (cannot be negative)

import itertools

param_grid = {
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1, 0.5],
    'n_estimators': [100, 150, 200, 300]
}

# Generate all parameter combinations
param_combinations = list(itertools.product(
    param_grid['max_depth'],
    param_grid['learning_rate'],
    param_grid['n_estimators']
))

results = []

# === Grid search loop ===
for (depth, lr, n_est) in tqdm(param_combinations, desc="Grid search progress"):
    params = {'max_depth': depth, 'learning_rate': lr, 'n_estimators': n_est}
    model = xgb.XGBRegressor(random_state=42, n_jobs=-1, **params)

    # --- Cross-validation R² ---
    cv_r2 = cross_val_score(model, X_train, y_train, cv=kf, scoring=r2_scorer, n_jobs=1).mean()

    # --- Train on full training set ---
    model.fit(X_train, y_train)
    y_train_pred = np.maximum(model.predict(X_train), 0)
    y_test_pred  = np.maximum(model.predict(X_test), 0)

    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)

    results.append({
        'max_depth': depth,
        'learning_rate': lr,
        'n_estimators': n_est,
        'Train_R2': train_r2,
        'CV_R2': cv_r2,
        'Test_R2': test_r2
    })

# === Compile results into a DataFrame ===
results_df = pd.DataFrame(results)
results_df = results_df.sort_values('CV_R2', ascending=False).reset_index(drop=True)

print("\n=== XGBoost Grid Search Results ===")
print(results_df.round(5))

# === Identify best configuration ===
best_params = results_df.iloc[0][['max_depth', 'learning_rate', 'n_estimators']].to_dict()
print(f"\nBest parameters: {best_params}")

import matplotlib.dates as mdates

# === 1. Refit model on all data ===
best_model = xgb.XGBRegressor(
    random_state=42,
    n_jobs=-1,
    n_estimators=300,
    max_depth=7,
    learning_rate=0.1
)
best_model.fit(X, y)

# === 2. Predict on the full dataset ===
y_pred_full = np.maximum(best_model.predict(X), 0)

# === 3. Combine with original data ===
plot_df = complete_df.copy()
plot_df['predicted'] = y_pred_full
plot_df['actual'] = plot_df['trip_count']

# === 4. Restore station names (from one-hot columns) ===
station_cols = [c for c in plot_df.columns if c.startswith('station_')]
plot_df['station'] = plot_df[station_cols].idxmax(axis=1).str.replace('station_', '')

# === 5. Sort by date and optionally smooth ===
plot_df = plot_df.sort_values('date')
plot_df['actual_smooth'] = plot_df['actual'].rolling(24, center=True).mean()
plot_df['predicted_smooth'] = plot_df['predicted'].rolling(24, center=True).mean()


# === 6. Plot setup ===
stations = plot_df['station'].unique()
n = len(stations)
plt.figure(figsize=(14, 3.5 * n))

for i, station in enumerate(stations, 1):
    subset = plot_df[plot_df['station'] == station]
    plt.subplot(n, 1, i)

    # Plot without CI and slightly offset predicted line for visual separation
    sns.lineplot(
        data=subset, x='date', y='actual_smooth',
        color='tab:blue', label='Actual', linewidth=1.5, errorbar=None
    )
    sns.lineplot(
        data=subset, x='date', y='predicted_smooth',
        color='tab:orange', label='Predicted', linewidth=1.5, errorbar=None, alpha=0.7
    )

    plt.title(station)
    plt.ylabel("Trip Count")
    plt.xlabel(None)
    plt.legend()

    # Monthly ticks, rotate labels
    ax = plt.gca()
    ax.xaxis.set_major_locator(mdates.MonthLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%b'))
    plt.xticks(rotation=45, ha='right')

    # Remove background gridlines
    ax.grid(False)

plt.suptitle("Actual vs Predicted Trip Counts by Station (Full Dataset, Smoothed Over Time)",
             fontsize=14, y=0.95)
plt.xlabel("Time (Monthly across the Year)")
plt.tight_layout(rect=[0, 0, 1, 0.94])
plt.show()

# Compute residuals
plot_df['residual'] = plot_df['actual'] - plot_df['predicted']

# Columns to show (only those that exist)
cols_to_show = [c for c in ['date', 'datetime', 'hour', 'station', 'actual', 'predicted', 'residual']
                if c in plot_df.columns]

# Sort for large positive and negative residuals
largest_positive = plot_df.sort_values('residual', ascending=False).head(20)
largest_negative = plot_df.sort_values('residual', ascending=True).head(20)

print("=== Top 20 Underpredicted (Actual >> Predicted) ===")
print(largest_positive[cols_to_show])

print("\n=== Top 20 Overpredicted (Predicted >> Actual) ===")
print(largest_negative[cols_to_show])

"""## Linear regression with weathercode"""

# Drop baseline dummies (to avoid multicollinearity)=
baseline_dummies = [
    'day_Monday',                                    # baseline for day_of_week
    'station_MIT at Mass Ave / Amherst St',          # baseline for station
    'week_1',                                        # baseline for week_of_year
    'hour_0',                                        # baseline for hour
    'weathercode_0'                                  # baseline for weathercode
]

# Drop these explicitly
X = X.drop(columns=baseline_dummies, errors='ignore')

for col in X.columns:
    print(col)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train linear regression
lr = LinearRegression()
lr.fit(X_train, y_train)

# Predict on both train and test
y_train_pred = lr.predict(X_train)
y_test_pred  = lr.predict(X_test)

# Compute metrics
train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
test_rmse  = np.sqrt(mean_squared_error(y_test, y_test_pred))
train_r2   = r2_score(y_train, y_train_pred)
test_r2    = r2_score(y_test, y_test_pred)

# Print results
print("Linear Regression Performance:")
print(f"Train RMSE: {train_rmse:.3f} | Train R²: {train_r2:.3f}")
print(f"Test  RMSE: {test_rmse:.3f} | Test  R²: {test_r2:.3f}")

# Inspect coefficients
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': lr.coef_
}).sort_values('Coefficient', ascending=False)

print("\nTop 10 positive predictors:")
print(coef_df.head(10))

print("\nTop 10 negative predictors:")
print(coef_df.tail(10))

# Fit OLS model on training data
ols_model = sm.OLS(y_train, X_train).fit()

# Predict on both training and test data
y_train_pred = ols_model.predict(X_train)
y_test_pred = ols_model.predict(X_test)

# Compute RMSE and R² for both sets
train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

# Print performance metrics
print(f"Train RMSE: {train_rmse:.3f}")
print(f"Train R²:   {train_r2:.3f}")
print(f"Test RMSE:  {test_rmse:.3f}")
print(f"Test R²:    {test_r2:.3f}\n")

# Print full regression summary
print(ols_model.summary())

print_ols_summary_with_stars(ols_model)

# Ridge and Lasso
# Split 80/20 for final evaluation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# CV setup
kf = KFold(n_splits=5, shuffle=True, random_state=42)
rmse_scorer = make_scorer(lambda y_true, y_pred: np.sqrt(mean_squared_error(y_true, y_pred)),
                          greater_is_better=False)
r2_scorer = make_scorer(r2_score)

# Model parameter grids
param_grid = {
    'Ridge': {'model': Ridge(), 'params': {'alpha': [0.0001, 0.001, 0.01, 0.1, 1, 5, 10]}},
    'Lasso': {'model': Lasso(max_iter=5000), 'params': {'alpha': [0.0001, 0.001, 0.01, 0.1]}},
}

# CV → best param → train/test evaluation
for name, entry in tqdm(param_grid.items(), desc="Model families"):
    print(f"\n\n===== {name} =====")
    base_model = entry['model']
    params = entry['params']
    param_results = []

    best_cv_r2 = -np.inf
    best_param = None
    best_model = None

    # --- Step 1: cross-validation for all parameters ---
    for param_name, param_values in params.items():
        for val in param_values:
            model = base_model.set_params(**{param_name: val})
            cv_r2 = cross_val_score(model, X_train, y_train, cv=kf, scoring=r2_scorer, n_jobs=-1).mean()
            param_results.append([f"{param_name}={val}", cv_r2])
            if cv_r2 > best_cv_r2:
                best_cv_r2 = cv_r2
                best_param = {param_name: val}
                best_model = model

    # --- Step 2: show CV R² for all parameters ---
    param_df = pd.DataFrame(param_results, columns=['Parameter', 'CV_R2'])
    print(param_df.round(3))
    print(f"\nBest parameter for {name}: {best_param} (CV_R²={best_cv_r2:.3f})")

    # --- Step 3: retrain best model on all training data ---
    best_model.fit(X_train, y_train)
    y_train_pred = best_model.predict(X_train)
    y_test_pred = best_model.predict(X_test)

    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)

    print(f"Train R²: {train_r2:.3f} | Test R²: {test_r2:.3f}")

"""# Aggregate trip (inbound/end station)"""

